apiVersion: apps/v1
kind: Deployment
metadata:
  name: bb-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cobaan
  template:
    metadata:
      labels:
        app: cobaan
    spec:
      containers:
      - name: coba
        image: piscesian/percobaan
